name: Auto-merge main into store branches

on:
  push:
    branches:
      - main
  workflow_dispatch: {}  # lets you run it manually from the Actions tab

permissions:
  contents: write

jobs:
  merge-main-into-stores:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch:
          - "store/uk"
          - "store/us"
          - "store/eu"
          - "store/row"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Merge main into ${{ matrix.branch }}
        run: |
          TARGET="${{ matrix.branch }}"

          git fetch origin

          # Update local main to match origin
          git checkout main
          git reset --hard origin/main

          # Update local target to match origin
          git checkout "$TARGET"
          git reset --hard "origin/$TARGET"

          # Merge main into target
          if ! git merge --no-ff --no-edit main; then
            echo "Merge conflict when merging main into $TARGET."
            echo "Resolve this merge manually in your local repo."
            exit 1
          fi

          # Push updated target branch
          git push origin "$TARGET"
